version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - revive
    - gosec
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
       - fieldalignment
    staticcheck:
      checks: ["all"]
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
  exclusions:
    paths:
      - vendor

run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 50
  max-same-issues: 50